---
- name: Deploy E-commerce Site
  hosts: all
  become: yes
  tasks:
    - name: Install Apache Web Server
      apt:
        name: apache2
        state: present
        update_cache: yes

    - name: Start and Enable Apache
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Copy website files to web root
      copy:
        src: index.html
        dest: /var/www/html/index.html
